name: Replace Names
on: push
jobs:
  replace_names:
    if: github.repository != 'QUARK-framework/QUARK-plugin-template'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Get repo url
        run: echo "REPO_URL=https$(echo '${{ github.repositoryUrl }}' | cut -c 4- | rev | cut -c 5- | rev)" >> $GITHUB_ENV

      - name: Get plugin name
        run: echo "PLUGIN_NAME=$(echo '${{ github.repository }}' | cut -d "/" -f2-)" >> $GITHUB_ENV

      - name: Get formatted plugin name
        run: echo "PLUGIN_NAME_FORMATTED=$(echo '${{ env.PLUGIN_NAME }}' | tr '-' ' ' | tr -s ' ' | tr ' ' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Find and replace formatted plugin name
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "PLUGIN_NAME_FORMATTED"
          replace: ${{ env.PLUGIN_NAME_FORMATTED }}
          regex: false
          exclude: .git*/**

      - name: Find and replace plugin name
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "PLUGIN_NAME"
          replace: ${{ env.PLUGIN_NAME }}
          regex: false
          exclude: .git*/**

      - name: Find and replace plugin homepage
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "PLUGIN_HOMEPAGE"
          replace: ${{ env.REPO_URL }}
          regex: false
          exclude: .git*/**

      - name: Rename directory
        run: mv src/PLUGIN_NAME_FORMATTED src/${{ env.PLUGIN_NAME_FORMATTED }}

      - name: Delete action
        run: rm -rf .github/workflows/replace_names.yml

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
